spring:
  application:
    name: "reconciliation-transactions-financieres"
  batch:
    job:
      enabled: false
  mongodb:
    uri: "mongodb://user:password@mongodb:27017/bank?authSource=admin"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG